functionsDirectory = "C:\\Users\\ansh0\\legal connect\\netlify\\functions"
functionsDirectoryOrigin = "default"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
edge_functions = "C:\\Users\\ansh0\\legal connect\\netlify\\edge-functions"
publish = "C:\\Users\\ansh0\\legal connect\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\Users\\ansh0\\legal connect\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[edge_functions]]
path = "/api/contact-lawyer"
function = "send-email"

[functions]

[functions."*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]